# frozen_string_literal: true

source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-autoprefixer'
gem 'middleman-dato', '0.5.14'
gem 'middleman-livereload'
gem 'middleman-search_engine_sitemap'
